### ISSUE TITLE
Retrait des utilisateurs Ex-membres des envois automatiques via le portail des clubs

### ISSUE THREAD

**Issue by fgcom** [Threesixty/aufo-jde-ppst#180]
Les utilisateurs ayant le statut ex-membre (ex. de Anthony DELTOUR) ne doivent pas être inclus dans les envois automatiques de mails via le portail des clubs, comme par exemple pour les questions sur le forum. A vérifier.

**Comment by Threesixty** [comment]
C'est corrigé, seul les membres "actifs" sont informés lors d'une nouvelle question FAQ et à la publication d'une nouvelle offre d'emploi.
