### ISSUE TITLE
Test avec Michael

### ISSUE THREAD

**Issue by vbrillot** [Threesixty/aufo-jde-ppst#181]
j'ouvre un ticket test
![screenshot 2016-02-10 at 18 12 06](https://cloud.githubusercontent.com/assets/17125253/12955105/d1e283da-d021-11e5-9c32-6626e3fdd2bc.png)

**Comment by Threesixty** [comment]
Pour que je recoive la notification il faut me l'attribuer 
![capture d ecran 2016-02-10 a 18 13 28](https://cloud.githubusercontent.com/assets/6042147/12955161/0b4dd28c-d022-11e5-9fe0-6096415f9332.png)

**Comment by Threesixty** [comment]
Bien reçu ! ;-)
